#!/bin/sh
set -eu

##############################################################################
# KDL JSON → HTML Report Generator
#
# Usage:
#   ./kdl-json-to-html.sh input.json output.html
##############################################################################

INPUT_JSON="${1:?Usage: $0 <input.json> <output.html>}"
OUTPUT_HTML="${2:?Usage: $0 <input.json> <output.html>}"

command -v jq >/dev/null 2>&1 || {
  echo "ERROR: jq is required" >&2
  exit 1
}

[ -f "$INPUT_JSON" ] || {
  echo "ERROR: Input JSON not found: $INPUT_JSON" >&2
  exit 1
}

jq -r '
def badge(v):
  if v == true then "<span class=\"badge ok\">Detected</span>"
  else "<span class=\"badge warn\">Not detected</span>" end;

def card(title; value):
  "<div class=\"card\"><strong>" + title + "</strong><br>" + value + "</div>";

"<!DOCTYPE html>
<html lang=\"en\">
<head>
<meta charset=\"UTF-8\">
<title>Kasten Discovery Lite Report</title>
<style>
body {
  font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Arial, sans-serif;
  background: #f6f8fa;
  color: #24292e;
  margin: 2rem;
}
h1, h2 {
  border-bottom: 1px solid #e1e4e8;
  padding-bottom: .3rem;
}
.grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: 1rem;
  margin-bottom: 1rem;
}
.card {
  background: #ffffff;
  border: 1px solid #e1e4e8;
  border-radius: 8px;
  padding: 1rem;
}
table {
  width: 100%;
  border-collapse: collapse;
  margin-top: .5rem;
}
th, td {
  border: 1px solid #e1e4e8;
  padding: .5rem;
  text-align: left;
}
th {
  background: #f0f3f6;
}
.badge {
  padding: .2rem .6rem;
  border-radius: 6px;
  font-size: .85rem;
}
.ok { background: #dafbe1; }
.warn { background: #fff8c5; }
.footer {
  margin-top: 2rem;
  font-size: .8rem;
  color: #57606a;
}
</style>
</head>
<body>

<h1>🔍 Kasten Discovery Lite</h1>

<div class=\"grid\">"
+
card("Platform"; .platform)
+
card("Kasten Version"; .kastenVersion)
+
card("Profiles"; (.profiles.count | tostring))
+
card("Policies"; (.policies.count | tostring))
+
"</div>

<h2>🔒 Immutability</h2>
<div class=\"card\">
Status: " + badge(.immutabilitySignal) +
(if .immutabilityDays != null then
  "<br>Protection period: " + (.immutabilityDays | tostring) + " days"
 else "" end) +
"</div>

<h2>📦 Profiles</h2>
<table>
<tr>
<th>Name</th><th>Backend</th><th>Region</th><th>Endpoint</th><th>Protection</th>
</tr>"
+
(.profiles.items | map(
  "<tr><td>" + .name +
  "</td><td>" + .backend +
  "</td><td>" + .region +
  "</td><td>" + .endpoint +
  "</td><td>" + (.protectionPeriod // "not set") +
  "</td></tr>"
) | join(""))
+
"</table>

<h2>📜 Policies</h2>
<table>
<tr>
<th>Name</th><th>Frequency</th><th>Namespaces</th><th>Retention</th>
</tr>"
+
(.policies.items | map(
  "<tr><td>" + .name +
  "</td><td>" + .frequency +
  "</td><td>" + (.namespaces | join(", ")) +
  "</td><td>" +
    (if (.retention | type) == "object" then
      (.retention | to_entries | map("\(.key): \(.value)") | join(", "))
     else
      "not defined"
     end) +
  "</td></tr>"
) | join(""))
+
"</table>

<h2>📊 Coverage Summary</h2>
<div class=\"card\">
Policies targeting all namespaces:
<strong>" + (.coverage.policiesTargetingAllNamespaces | tostring) + "</strong>
</div>

<div class=\"footer\">
Generated by Kasten Discovery Lite
</div>

</body>
</html>"
' "$INPUT_JSON" > "$OUTPUT_HTML"

echo "✅ HTML report generated: $OUTPUT_HTML"
